# Wine Quality Prediction

# Importing Libraries

In [5]:
import numpy as np 
import pandas as pd 
import seaborn as sns
import matplotlib.pyplot as plt

# Reading Dataset

In [6]:
data = pd.read_csv("winequality.csv")
data.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [7]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

In [8]:
data.describe()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
count,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000,1599.000000
mean,8.319637,0.527821,0.270976,2.538806,0.087467,15.874922,46.467792,0.996747,3.311113,0.658149,10.422983,5.636023
std,1.741096,0.179060,0.194801,1.409928,0.047065,10.460157,32.895324,0.001887,0.154386,0.169507,1.065668,0.807569
min,4.600000,0.120000,0.000000,0.900000,0.012000,1.000000,6.000000,0.990070,2.740000,0.330000,8.400000,3.000000
25%,7.100000,0.390000,0.090000,1.900000,0.070000,7.000000,22.000000,0.995600,3.210000,0.550000,9.500000,5.000000
50%,7.900000,0.520000,0.260000,2.200000,0.079000,14.000000,38.000000,0.996750,3.310000,0.620000,10.200000,6.000000
75%,9.200000,0.640000,0.420000,2.600000,0.090000,21.000000,62.000000,0.997835,3.400000,0.730000,11.100000,6.000000
max,15.900000,1.580000,1.000000,15.500000,0.611000,72.000000,289.000000,1.003690,4.010000,2.000000,14.900000,8.000000

In [ ]:
sns.pairplot(data)

In [ ]:
sns.heatmap(data.corr())
plt.show()

In [ ]:
correlations = data.corr()['quality'].drop('quality')
print(correlations)

In [8]:
def get_features(correlation_threshold):
    abs_corrs = correlations.abs()
    high_correlations = abs_corrs[abs_corrs > correlation_threshold].index.values.tolist()
    return high_correlations

In [9]:
features = get_features(0.05) 
print(features)

['fixed acidity', 'volatile acidity', 'citric acid', 'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density', 'pH', 'sulphates', 'alcohol']

In [10]:
x = data[features]
y = data['quality']

In [11]:
x

,fixed acidity,volatile acidity,citric acid,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol
0,7.4,0.700,0.00,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
1,7.8,0.880,0.00,0.098,25.0,67.0,0.99680,3.20,0.68,9.8
2,7.8,0.760,0.04,0.092,15.0,54.0,0.99700,3.26,0.65,9.8
3,11.2,0.280,0.56,0.075,17.0,60.0,0.99800,3.16,0.58,9.8
4,7.4,0.700,0.00,0.076,11.0,34.0,0.99780,3.51,0.56,9.4
...,...,...,...,...,...,...,...,...,...,...
1594,6.2,0.600,0.08,0.090,32.0,44.0,0.99490,3.45,0.58,10.5
1595,5.9,0.550,0.10,0.062,39.0,51.0,0.99512,3.52,0.76,11.2
1596,6.3,0.510,0.13,0.076,29.0,40.0,0.99574,3.42,0.75,11.0
1597,5.9,0.645,0.12,0.075,32.0,44.0,0.99547,3.57,0.71,10.2
1598,6.0,0.310,0.47,0.067,18.0,42.0,0.99549,3.39,0.66,11.0

In [12]:
y

0       5
1       5
2       5
3       6
4       5
       ..
1594    5
1595    6
1596    6
1597    5
1598    6
Name: quality, Length: 1599, dtype: int64

In [13]:
from sklearn.model_selection import train_test_split

# Splitting Training and Testing Data

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=3)

In [15]:
x_train.shape

(1199, 10)

# Linear Regression Model

In [16]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [17]:
train_pred = lr.predict(x_train)
print(train_pred)

[5.33777144 5.33826411 5.9503318  ... 6.3903182  6.19979375 5.27597259]

In [18]:
test_pred = lr.predict(x_test)
print(test_pred)

[5.10801475 5.65933623 5.90407267 6.13461179 5.00611866 5.44514691
 5.05735245 6.15497513 5.51919603 5.77259374 5.61809366 5.23616173
 5.23544213 5.31968644 6.47007277 5.043404   5.85287121 5.19427909
 6.07727089 6.34949018 6.42525555 5.51221957 5.8030796  4.93637817
 5.16618356 5.48255293 5.13758624 6.60000969 5.88754763 5.74133915
 6.09716961 6.29379754 4.91269821 5.88611904 5.11007273 5.94574773
 6.80685536 5.04305653 5.25438683 5.88611904 5.17406542 4.84008442
 6.48781656 5.40521715 5.31105571 5.84484462 5.7100681  5.24300809
 5.25021217 5.46398911 5.08740494 5.61369555 6.01375792 6.32497377
 5.47511954 5.36466869 5.09234555 4.92625623 5.21415941 5.08274744
 4.79570013 5.4377645  5.25237771 5.68830391 5.85145609 6.52420079
 5.38691412 5.71775637 5.17641417 5.99156845 5.6445189  5.60892012
 5.74967567 5.21702288 5.97975854 5.51115845 5.41121547 5.6832459
 5.63971524 5.74133915 6.24163428 5.27915822 4.66596769 6.04951743
 5.52401618 5.17823915 5.20672986 5.96322663 5.50411353 5.64866275
 5.70105618 5.6431575  5.72586828 5.3173125  5.37075392 5.394889
 4.82061159 5.46006525 5.47363879 6.54074801 6.13723937 5.61422461
 6.07821503 6.17461539 5.73230665 4.92692198 4.73317591 5.03851027
 5.44868797 5.78432759 6.46608259 5.47530673 6.46876056 5.94466642
 5.43257493 5.20523855 5.34551741 5.20749557 6.19344578 5.61453943
 5.83308923 5.20267759 5.17702922 5.26912156 5.74382704 5.6431575
 6.15450941 5.89677877 5.49186029 5.39047629 5.25848318 5.41150099
 5.70750135 5.68001376 6.58288921 5.89497164 6.37172338 5.72945992
 5.37936908 5.14371952 5.58851063 6.59661777 5.24403336 5.25594627
 5.54721935 5.17243958 5.76990082 6.10847777 6.93985005 4.99562031
 5.01958735 4.68547026 5.82434616 5.01708671 5.21702288 5.70819215
 5.63334181 5.33481542 5.22220103 5.84327644 5.61823023 5.78078643
 5.51830906 6.03898671 5.63808482 5.49193476 5.96787582 4.82363567
 5.26331016 5.6625652  5.73510278 6.59570394 5.02584187 5.9062506
 5.85381667 5.21140744 5.68951564 5.51649995 5.40521715 6.37974889
 6.71642336 4.98858413 5.88413601 5.75553621 5.75508093 5.61677128
 5.71318209 5.40944809 6.05634078 5.58276397 5.88366084 6.51928901
 5.00668628 5.4022397  5.18103224 5.17641417 5.47511954 5.7498414
 5.69035164 4.92770738 5.12908401 4.98756458 6.18242395 5.65384546
 5.45261211 5.56461849 4.99367423 5.8451887  5.31537513 5.48096741
 5.69721582 5.63441998 5.69158339 5.82596777 5.79120742 6.02976291
 6.20119324 5.2711036  5.04432824 5.21865445 5.38560996 4.97814926
 6.21495495 5.44287205 5.94855371 5.21554859 6.61250215 5.08358009
 5.29397027 5.0345619  6.16924449 5.78078489 4.85807345 5.74347603
 5.29957538 5.35504601 5.17674741 6.30056659 5.58203663 4.95859588
 6.10234044 6.03135183 6.16235396 5.41939397 6.76220041 6.20905743
 6.08858508 5.2295158  5.45339068 5.54357835 5.35504601 5.24163328
 5.74950618 5.25054347 6.1317778  5.42684978 5.84929436 4.82101128
 6.06442799 5.06580635 6.43296901 6.06017586 5.69914195 5.70750135
 4.90849494 6.00470504 5.28204515 5.70851728 5.42245606 5.12401141
 6.4859156  5.3065303  5.97368396 5.64309435 6.49134579 6.20544121
 5.09817253 5.47044255 5.30164692 5.24148223 6.37172338 5.38111102
 5.41238036 6.00040309 4.98474017 5.89003832 5.35695446 5.18204386
 5.43418226 5.92040958 4.83001281 6.84476407 5.17004942 4.90738182
 5.71686848 5.6789345  5.30006437 6.28821696 6.8852049  6.5809374
 5.94544069 6.3372236  5.90511355 5.56832499 6.0037674  5.51592572
 5.47416032 5.73230665 5.31523101 5.15200739 6.22058683 5.30080495
 6.2234137  6.09823805 5.86965547 5.42671619 4.83521332 6.04105625
 5.17954177 5.11991572 6.45483786 5.50117269 6.75189479 5.112668
 5.16698378 5.30775351 5.71062442 5.10611189 5.54132974 5.3123985
 5.16102307 4.95778371 5.4565424  5.38281735 5.34456446 5.18064244
 6.11817384 5.624629   5.7335454  6.34845774 5.90187012 5.51649995
 5.69382597 5.14872878 5.70431206 6.40518994 6.17170859 5.46670957
 6.06382552 5.69529022 6.24040985 5.24148223 5.5445765  5.04703379
 4.99563993 5.07398398 5.81020153 5.40277302 5.9958201  5.1304824
 6.51949038 5.39875246 5.49117974 5.64759732 5.52711217 5.27288466
 6.49134579 5.83141585 5.03473182 5.24121201 5.49075176 5.27342775
 5.5118796  5.04396982 5.29167137 5.46007816 5.36402691 6.12719352
 4.99200331 5.30164692 6.08655307 5.20523855 5.13058231 4.66155684
 6.15823093 6.15917286 6.50582017 5.80335212 5.74347603 6.39828821
 6.14436092 5.88754763 6.05466721 6.03231119 5.36683868 5.41989769
 5.61706715 5.4057693  5.76283208 5.2734642 ]

In [19]:
from sklearn  import metrics

In [20]:
train_rms = metrics.mean_squared_error(train_pred, y_train)**0.5

In [21]:
train_rms

0.6525240995947054

In [22]:
test_rmse = metrics.mean_squared_error(test_pred, y_test) ** 0.5
print(test_rmse)

0.6275381539230979

In [23]:
# rounding off the predicted values for test set
predicted_data = np.round_(test_pred)
print(predicted_data)
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, test_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, test_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, test_pred)))
# displaying coefficients of each feature
coeffecients = pd.DataFrame(lr.coef_,features) 
coeffecients.columns = ['Coeffecient'] 
print(coeffecients)

[5. 6. 6. 6. 5. 5. 5. 6. 6. 6. 6. 5. 5. 5. 6. 5. 6. 5. 6. 6. 6. 6. 6. 5.
 5. 5. 5. 7. 6. 6. 6. 6. 5. 6. 5. 6. 7. 5. 5. 6. 5. 5. 6. 5. 5. 6. 6. 5.
 5. 5. 5. 6. 6. 6. 5. 5. 5. 5. 5. 5. 5. 5. 5. 6. 6. 7. 5. 6. 5. 6. 6. 6.
 6. 5. 6. 6. 5. 6. 6. 6. 6. 5. 5. 6. 6. 5. 5. 6. 6. 6. 6. 6. 6. 5. 5. 5.
 5. 5. 5. 7. 6. 6. 6. 6. 6. 5. 5. 5. 5. 6. 6. 5. 6. 6. 5. 5. 5. 5. 6. 6.
 6. 5. 5. 5. 6. 6. 6. 6. 5. 5. 5. 5. 6. 6. 7. 6. 6. 6. 5. 5. 6. 7. 5. 5.
 6. 5. 6. 6. 7. 5. 5. 5. 6. 5. 5. 6. 6. 5. 5. 6. 6. 6. 6. 6. 6. 5. 6. 5.
 5. 6. 6. 7. 5. 6. 6. 5. 6. 6. 5. 6. 7. 5. 6. 6. 6. 6. 6. 5. 6. 6. 6. 7.
 5. 5. 5. 5. 5. 6. 6. 5. 5. 5. 6. 6. 5. 6. 5. 6. 5. 5. 6. 6. 6. 6. 6. 6.
 6. 5. 5. 5. 5. 5. 6. 5. 6. 5. 7. 5. 5. 5. 6. 6. 5. 6. 5. 5. 5. 6. 6. 5.
 6. 6. 6. 5. 7. 6. 6. 5. 5. 6. 5. 5. 6. 5. 6. 5. 6. 5. 6. 5. 6. 6. 6. 6.
 5. 6. 5. 6. 5. 5. 6. 5. 6. 6. 6. 6. 5. 5. 5. 5. 6. 5. 5. 6. 5. 6. 5. 5.
 5. 6. 5. 7. 5. 5. 6. 6. 5. 6. 7. 7. 6. 6. 6. 6. 6. 6. 5. 6. 5. 5. 6. 5.
 6. 6. 6. 5. 5. 6. 5. 5. 6. 6. 7. 5. 5. 5. 6. 5. 6. 5. 5. 5. 5. 5. 5. 5.
 6. 6. 6. 6. 6. 6. 6. 5. 6. 6. 6. 5. 6. 6. 6. 5. 6. 5. 5. 5. 6. 5. 6. 5.
 7. 5. 5. 6. 6. 5. 6. 6. 5. 5. 5. 5. 6. 5. 5. 5. 5. 6. 5. 5. 6. 5. 5. 5.
 6. 6. 7. 6. 6. 6. 6. 6. 6. 6. 5. 5. 6. 5. 6. 5.]
Mean Absolute Error: 0.48443407559847146
Mean Squared Error: 0.3938041346292096
Root Mean Squared Error: 0.6275381539230979
                      Coeffecient
fixed acidity            0.017737
volatile acidity        -0.992560
citric acid             -0.139629
chlorides               -1.590943
free sulfur dioxide      0.005597
total sulfur dioxide    -0.003520
density                  0.768590
pH                      -0.437414
sulphates                0.812888
alcohol                  0.301484

In [25]:
coeffecients = pd.DataFrame(lr.coef_,features)
coeffecients.columns = ['Coeffecient']
coeffecients

                      Coeffecient
fixed acidity            0.017737
volatile acidity        -0.992560
citric acid             -0.139629
chlorides               -1.590943
free sulfur dioxide      0.005597
total sulfur dioxide    -0.003520
density                  0.768590
pH                      -0.437414
sulphates                0.812888
alcohol                  0.301484